# Generated by Django 4.2.10 on 2024-02-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.PositiveIntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("date", models.DateField()),
                (
                    "people",
                    models.IntegerField(
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                        ]
                    ),
                ),
                (
                    "time",
                    models.CharField(
                        choices=[
                            ("10", "10"),
                            ("12", "12"),
                            ("14", "14"),
                            ("16", "16"),
                            ("18", "18"),
                            ("12", "12"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
