# Generated by Django 4.2.10 on 2024-02-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_alter_reservation_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="time",
            field=models.CharField(
                choices=[
                    ("10", "10"),
                    ("12", "12"),
                    ("14", "14"),
                    ("16", "16"),
                    ("18", "18"),
                    ("20", "20"),
                ],
                max_length=10,
            ),
        ),
    ]
