# Generated by Django 4.2.10 on 2024-02-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_alter_reservation_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation", name="people", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="reservation", name="time", field=models.IntegerField(),
        ),
    ]
