# Generated by Django 4.2.10 on 2024-02-12 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_faq"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[("b", "brakefast"), ("l", "lunch"), ("d", "dinner")],
                        max_length=255,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discount", models.FloatField()),
                ("description", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="FoodMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("amount", models.CharField(max_length=100)),
                (
                    "rate",
                    models.IntegerField(
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                        ]
                    ),
                ),
                ("slug", models.SlugField()),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=15)),
                ("inventory", models.IntegerField()),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="pages.category",
                    ),
                ),
                ("discounts", models.ManyToManyField(blank=True, to="pages.discount")),
            ],
        ),
    ]
