# Generated by Django 4.2.10 on 2024-02-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_category_discount_foodmenu"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodmenu",
            name="image",
            field=models.ImageField(blank=True, upload_to="foods/"),
        ),
    ]
