# Generated by Django 4.2.10 on 2024-02-13 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_foodmenu_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodmenu",
            name="categorie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="pages.category"
            ),
        ),
    ]
