# Generated by Django 4.2.10 on 2024-02-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_alter_foodmenu_categorie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(
                choices=[
                    ("brakefast", "brakefast"),
                    ("lunch", "lunch"),
                    ("dinner", "dinner"),
                ],
                max_length=255,
            ),
        ),
    ]
