# Generated by Django 4.2.10 on 2024-02-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0009_alter_category_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodmenu",
            name="rate",
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
