# Generated by Django 4.2.10 on 2024-02-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0010_alter_foodmenu_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodmenu", name="price", field=models.PositiveBigIntegerField(),
        ),
    ]
