# Generated by Django 4.2.10 on 2024-02-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0011_alter_foodmenu_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("phone", models.IntegerField()),
            ],
        ),
    ]
