# Generated by Django 4.2.10 on 2024-02-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0012_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodmenu", name="price", field=models.IntegerField(),
        ),
    ]
