# Generated by Django 4.2.10 on 2024-02-19 09:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0013_alter_foodmenu_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodmenu",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
