# Generated by Django 4.2.10 on 2024-02-19 20:03

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description", ckeditor.fields.RichTextField()),
                ("description2", ckeditor.fields.RichTextField()),
                ("tips", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("author_note", models.TextField()),
                (
                    "image_cover",
                    models.ImageField(blank=True, upload_to="blog_covers/"),
                ),
                (
                    "image_detail",
                    models.ImageField(blank=True, upload_to="blog_covers/"),
                ),
                (
                    "image_detail2",
                    models.ImageField(blank=True, upload_to="blog_covers/"),
                ),
                (
                    "image_detail3",
                    models.ImageField(blank=True, upload_to="blog_covers/"),
                ),
                ("datetime_created", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Draft"), (1, "Publish")], default=0
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=60)),
                ("body", models.TextField()),
                ("datetime_commented", models.DateTimeField(auto_now_add=True)),
                ("phone_number", models.IntegerField(max_length=10)),
                ("email", models.EmailField(max_length=254)),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="blogs.blog",
                    ),
                ),
            ],
        ),
    ]
